//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activei {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\Downloaded Program Files")]
        public string DownloadedProgramFilesPath {
            get {
                return ((string)(this["DownloadedProgramFilesPath"]));
            }
            set {
                this["DownloadedProgramFilesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\Minidump|C:\\Windows\\Temp|C:\\Windows\\Downloaded Program Files")]
        public string JunkFilePath {
            get {
                return ((string)(this["JunkFilePath"]));
            }
            set {
                this["JunkFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string rememberPassword {
            get {
                return ((string)(this["rememberPassword"]));
            }
            set {
                this["rememberPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<table class=\"diskanalTable\" border=\"1\"  cellspacing=\"0\" cellpadding=\"0\"><tbody>{" +
            "$driveinfo$}</tbody></table>")]
        public string DiskAnalysisTemplate {
            get {
                return ((string)(this["DiskAnalysisTemplate"]));
            }
            set {
                this["DiskAnalysisTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
<tr><th colspan=""2"" style=""text-align:left"">{$drivename$}</th></tr><tr><td>Volume size</td><td>{$volumesize$}</td></tr><tr><td>Free space</td><td>{$freespace$}</td></tr><tr><td>Total fragmented space</td><td>{$fragmentedspace$}</td></tr><tr><td>Largest free space size</td><td>{$largestfreespacesize$}</td></tr><tr><td>Status</td><td>{$status$}</td></tr>")]
        public string DriveTemplate {
            get {
                return ((string)(this["DriveTemplate"]));
            }
            set {
                this["DriveTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$driveinfo$}")]
        public string DriveInfo {
            get {
                return ((string)(this["DriveInfo"]));
            }
            set {
                this["DriveInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$drivename$}")]
        public string DriveName {
            get {
                return ((string)(this["DriveName"]));
            }
            set {
                this["DriveName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$volumesize$}")]
        public string VolumeSize {
            get {
                return ((string)(this["VolumeSize"]));
            }
            set {
                this["VolumeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$freespace$}")]
        public string FreeSpace {
            get {
                return ((string)(this["FreeSpace"]));
            }
            set {
                this["FreeSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$fragmentedspace$}")]
        public string FragmentedSpace {
            get {
                return ((string)(this["FragmentedSpace"]));
            }
            set {
                this["FragmentedSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$status$}")]
        public string Status {
            get {
                return ((string)(this["Status"]));
            }
            set {
                this["Status"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$largestfreespacesize$}")]
        public string LargestFreeSpace {
            get {
                return ((string)(this["LargestFreeSpace"]));
            }
            set {
                this["LargestFreeSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<body bgcolor=""#8e7b98"" style=""font-family:'Segoe UI',Trebuchet MS,Arial;""><table border=""1"" cellspacing=""0"" cellpadding=""0"" style=""transparent;border-collapse:collapse;width:100%;background-color:#eee;font-
family:'Segoe UI',Trebuchet MS,Arial;font-size: 12px;""><tr><th colspan=""3"" style=""background:#222433;color:#fff;"">Defragmentation Report</th></tr>{$driveinfo$}</table></body>")]
        public string DefragTemplate {
            get {
                return ((string)(this["DefragTemplate"]));
            }
            set {
                this["DefragTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<tr><th colspan=""3"" style=""text-align:left; background:#222433;color:#fff;"">{$drivename$}</th></tr><tr><tr><th></th><th style=""background:#222433;color:#fff;"">Before</th><th style=""background:#222433;color:#fff;"">After</th></tr><tr><td>Volume size</td><td>{$volumesize$}</td><td>{$aftervolumesize$}</td></tr><tr></tr><tr><td>Cluster size</td><td>{$clustersize$}</td><td>{$afterclustersize$}</td></tr><tr><td>Used space</td><td>{$usedspace$}</td><td>{$afterusedspace$}</td></tr><tr><td>Free space</td><td>{$freespace$}</td><td>{$afterfreespace$}</td></tr><tr><td>Total fragmented space</td><td>{$fragmentedspace$}</td><td>{$afterfragmentedspace$}</td></tr>")]
        public string DefragDriveTemplate {
            get {
                return ((string)(this["DefragDriveTemplate"]));
            }
            set {
                this["DefragDriveTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$aftervolumesize$}")]
        public string AfterVolumeSize {
            get {
                return ((string)(this["AfterVolumeSize"]));
            }
            set {
                this["AfterVolumeSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$afterfreespace$}")]
        public string AfterFreeSpace {
            get {
                return ((string)(this["AfterFreeSpace"]));
            }
            set {
                this["AfterFreeSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$usedspace$}")]
        public string UsedSpace {
            get {
                return ((string)(this["UsedSpace"]));
            }
            set {
                this["UsedSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$afterusedspace$}")]
        public string AfterUsedSpace {
            get {
                return ((string)(this["AfterUsedSpace"]));
            }
            set {
                this["AfterUsedSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$afterfragmentedspace$}")]
        public string AfterFragmentedSpace {
            get {
                return ((string)(this["AfterFragmentedSpace"]));
            }
            set {
                this["AfterFragmentedSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$clustersize$}")]
        public string ClusterSize {
            get {
                return ((string)(this["ClusterSize"]));
            }
            set {
                this["ClusterSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$afterclustersize$}")]
        public string AfterClusterSize {
            get {
                return ((string)(this["AfterClusterSize"]));
            }
            set {
                this["AfterClusterSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<body bgcolor=""#8e7b98"" style=""font-family:'Segoe UI',Trebuchet MS,Arial;""><table border=""1"" cellspacing=""0"" cellpadding=""0"" style=""transparent;border-collapse:collapse;width:100%;background-color:#eee;border-color:#fff;font-
family:'Segoe UI',Trebuchet MS,Arial;font-size: 12px;Height:10vw"">{$driveinfo$}</table></body>")]
        public string DefragAnalysisTemplate {
            get {
                return ((string)(this["DefragAnalysisTemplate"]));
            }
            set {
                this["DefragAnalysisTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<tr><th colspan=""2"" style=""text-align:left; style=""background-color:#d7d7d7;color:#fff;"""">{$drivename$}</th></tr><tr><td>Volume size</td><td>{$volumesize$}</td></tr><tr><td>Cluster size</td><td>{$clustersize$}</td></tr><tr><td>Used space</td><td>{$usedspace$}</td></tr><tr><td>Free space</td><td>{$freespace$}</td></tr><tr><td>Total fragmented space</td><td>{$fragmentedspace$}</td></tr><tr><td>Status</td><td>{$status$}</td>")]
        public string DefragAnalysisDriveTemplate {
            get {
                return ((string)(this["DefragAnalysisDriveTemplate"]));
            }
            set {
                this["DefragAnalysisDriveTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<tr style=\"color:#000;\"><td>{$name$}</td><td>{$strength$}</td><td>{$status$}</td>" +
            "<td width=\"70%\">{$MacId$}</td><td>{$Rssid$}</td><td>{$BSSType$}</td><td>{$AuthAl" +
            "gorithm$}</td><td>{$CipherAlgorithm$}</td></tr>")]
        public string wifidetails {
            get {
                return ((string)(this["wifidetails"]));
            }
            set {
                this["wifidetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$wifidetails$}")]
        public string wifidetailsKey {
            get {
                return ((string)(this["wifidetailsKey"]));
            }
            set {
                this["wifidetailsKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<body style=""background-color:'grey';color:#000;font-family:'Segoe UI',Trebuchet MS,Arial;""><div class=""row""><label for=""currentChannel"" class=""col-sm-4 control-label"">Current Channel:</label><label for=""channelRate"" class=""col-sm-2 control-label"">{$channelRate}</label></div><div class=""row""><label for=""noofNetwork"" class=""col-sm-4 control-label"">No of Networks connected:</label>{$networkConnected}</div><div class=""row""><label for=""signalQuality"" class=""col-sm-4 control-label"">Signal Quality:</label>{$networkQuality}</div></body>")]
        public string wifiChannelDetails {
            get {
                return ((string)(this["wifiChannelDetails"]));
            }
            set {
                this["wifiChannelDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$wifiChannelDetails$}")]
        public string wifiChannelDetailsKey {
            get {
                return ((string)(this["wifiChannelDetailsKey"]));
            }
            set {
                this["wifiChannelDetailsKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$wifiChannelLst$}")]
        public string wifiChannelListKey {
            get {
                return ((string)(this["wifiChannelListKey"]));
            }
            set {
                this["wifiChannelListKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<tr><td>{$channelNumber$}</td><td>{$numberofNetworks$}</td><td>{$channelQuality$}" +
            "</td></tr>")]
        public string wifiChannelTable {
            get {
                return ((string)(this["wifiChannelTable"]));
            }
            set {
                this["wifiChannelTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<body style=""background-color:'grey';color:#000;font-family:'Segoe UI',Trebuchet MS,Arial;""><div id=""wifiDetailsTbl""><table class=""table table-bordered"" style=""transparent;border-collapse:collapse;width:100%;font-
family:'Segoe UI',Trebuchet MS,Arial; ""><thead style=""color:#000;""><tr><th style=""font-weight:bold !important;"">Name</th><th style=""font-weight:bold !important;"">Strength</th><th style=""font-weight:bold !important;"">Status</th><th style=""font-weight:bold !important;"">MAC Address</th><th style=""font-weight:bold !important;"">RSSID</th><th style=""font-weight:bold !important;"">BSS Type</th><th style=""font-weight:bold !important;"">Default Algorithm</th><th style=""font-weight:bold !important;"">Cipher Algorithm</th></thead><tbody style=""color:#fff;"">{$wifidetails$}</tbody></table></div></body>")]
        public string wifitemplate {
            get {
                return ((string)(this["wifitemplate"]));
            }
            set {
                this["wifitemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{$wifiChannelDetails$}<body  style=""background-color:'grey';font-family:'Segoe UI',Trebuchet MS,Arial;""><div id=""wifiChannelTbl""><table class=""table table-bordered"" style=""transparent;border-collapse:collapse;width:100%;font-
family:'Segoe UI',Trebuchet MS,Arial; font-size: 12px; ""><thead style=""color:#000;""><tr><th style=""font-weight:bold !important;"">Channel</th><th style=""font-weight:bold !important;"">Number of Networks</th><th style=""font-weight:bold !important;"">Quality</th></thead><tbody>{$wifiChannelLst$}</tbody></table></div></body>")]
        public string wifiChannel {
            get {
                return ((string)(this["wifiChannel"]));
            }
            set {
                this["wifiChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<body bgcolor=""#8e7b98"" style=""font-family:'Segoe UI',Trebuchet MS,Arial;""><table border=""1"" cellspacing=""0"" cellpadding=""0"" style=""transparent;border-collapse:collapse;width:100%;background-color:#eee;font-
family:'Segoe UI',Trebuchet MS,Arial;font-size: 12px;""><tr><th colspan=""2"" style=""background:#222433;color:#fff;"">Disk Analysis/Defrag Report</th></tr><tr><th colspan=""2"" style=""background:#222433;color:#fff;"">{$error$}</th></tr></table></body>")]
        public string defragerrortemplate {
            get {
                return ((string)(this["defragerrortemplate"]));
            }
            set {
                this["defragerrortemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Unauthorized")]
        public string HttpUnauthorizedStatusCode {
            get {
                return ((string)(this["HttpUnauthorizedStatusCode"]));
            }
            set {
                this["HttpUnauthorizedStatusCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NameResolutionFailure\t")]
        public string HttpNameResolutionFailure {
            get {
                return ((string)(this["HttpNameResolutionFailure"]));
            }
            set {
                this["HttpNameResolutionFailure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
<table  class=""table table-bordered wifiDetailsTable"" style=""transparent;border-collapse:collapse;height:10vw;width:100%;font-family:'Segoe UI',Trebuchet MS,Arial; "">
<thead style=""color: #000; background-color: #d7d7d7;"">
<th style=""font-weight:bold !important;"">Adapter</th>
<th style=""font-weight:bold !important;"">MAC Address</th>
<th style=""font-weight:bold !important;"">Data Used(Mb)</th>
<th style=""font-weight:bold !important;"">Date</th>
</thead>
<tbody>
{$usageDetails$}
</tbody>
</table>
")]
        public string networkUsage {
            get {
                return ((string)(this["networkUsage"]));
            }
            set {
                this["networkUsage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{$usageDetails$}")]
        public string networkUsageKey {
            get {
                return ((string)(this["networkUsageKey"]));
            }
            set {
                this["networkUsageKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<tr><td>{$adapterName$}</td><td>{$macAddress$}</td><td>{$usage$}</td><td>{$usageD" +
            "ate$}</td></tr>")]
        public string networkUsageTable {
            get {
                return ((string)(this["networkUsageTable"]));
            }
            set {
                this["networkUsageTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("true")]
        public string userlogout {
            get {
                return ((string)(this["userlogout"]));
            }
            set {
                this["userlogout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FirstName {
            get {
                return ((string)(this["FirstName"]));
            }
            set {
                this["FirstName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RemainingDays {
            get {
                return ((string)(this["RemainingDays"]));
            }
            set {
                this["RemainingDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IsNetwork {
            get {
                return ((string)(this["IsNetwork"]));
            }
            set {
                this["IsNetwork"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ContractAvailability {
            get {
                return ((string)(this["ContractAvailability"]));
            }
            set {
                this["ContractAvailability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string IsNetworkChanged {
            get {
                return ((string)(this["IsNetworkChanged"]));
            }
            set {
                this["IsNetworkChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VersionInfo {
            get {
                return ((string)(this["VersionInfo"]));
            }
            set {
                this["VersionInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RouterUserName {
            get {
                return ((string)(this["RouterUserName"]));
            }
            set {
                this["RouterUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RouterPassword {
            get {
                return ((string)(this["RouterPassword"]));
            }
            set {
                this["RouterPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://routerlogin.com/soap/server_sa/")]
        public string RouterSoapUrl {
            get {
                return ((string)(this["RouterSoapUrl"]));
            }
            set {
                this["RouterSoapUrl"] = value;
            }
        }
    }
}
