//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activei.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Activei.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Activei {
            get {
                object obj = ResourceManager.GetObject("Activei", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Activei_Tray {
            get {
                object obj = ResourceManager.GetObject("Activei_Tray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activei is still running, you can click on the tray icon to launch it at any time..
        /// </summary>
        internal static string BaloonToolTipActivei {
            get {
                return ResourceManager.GetString("BaloonToolTipActivei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GearHead Connect is still running, you can click on the tray icon to launch it at any time..
        /// </summary>
        internal static string BaloonToolTipGearHead {
            get {
                return ResourceManager.GetString("BaloonToolTipGearHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close Activei ?.
        /// </summary>
        internal static string exitTextActivei {
            get {
                return ResourceManager.GetString("exitTextActivei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to close GearHead Connect ?.
        /// </summary>
        internal static string exitTextGearHead {
            get {
                return ResourceManager.GetString("exitTextGearHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gearhead_loader {
            get {
                object obj = ResourceManager.GetObject("gearhead_loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info {
            get {
                object obj = ResourceManager.GetObject("info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Disconnected.
        /// </summary>
        internal static string InternetStatusOff {
            get {
                return ResourceManager.GetString("InternetStatusOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connected.
        /// </summary>
        internal static string InternetStatusOn {
            get {
                return ResourceManager.GetString("InternetStatusOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loader {
            get {
                object obj = ResourceManager.GetObject("loader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string LogoutLabel {
            get {
                return ResourceManager.GetString("LogoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Webpage!!.
        /// </summary>
        internal static string MainWindow_browser_Navigating_Loading_Webpage {
            get {
                return ResourceManager.GetString("MainWindow_browser_Navigating_Loading_Webpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Webpage !!.
        /// </summary>
        internal static string MainWindow_browser_Navigating_Loading_Webpage___ {
            get {
                return ResourceManager.GetString("MainWindow_browser_Navigating_Loading_Webpage___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MainWindow_NotifyIcon__Open {
            get {
                return ResourceManager.GetString("MainWindow_NotifyIcon__Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string MainWindow_NotifyIcon__Uninstall {
            get {
                return ResourceManager.GetString("MainWindow_NotifyIcon__Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activei.
        /// </summary>
        internal static string MainWindow_NotifyIcon_Activei {
            get {
                return ResourceManager.GetString("MainWindow_NotifyIcon_Activei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MainWindow_NotifyIcon_E_xit {
            get {
                return ResourceManager.GetString("MainWindow_NotifyIcon_E_xit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GearHead Connect.
        /// </summary>
        internal static string MainWindow_NotifyIcon_Netgear {
            get {
                return ResourceManager.GetString("MainWindow_NotifyIcon_Netgear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NetGear_Tray {
            get {
                object obj = ResourceManager.GetObject("NetGear_Tray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NG_db {
            get {
                object obj = ResourceManager.GetObject("NG_db", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NG_Icon {
            get {
                object obj = ResourceManager.GetObject("NG_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon NGTray {
            get {
                object obj = ResourceManager.GetObject("NGTray", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        internal static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove the application from this computer?.
        /// </summary>
        internal static string Uninstall_Question {
            get {
                return ResourceManager.GetString("Uninstall_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uploadimg {
            get {
                object obj = ResourceManager.GetObject("uploadimg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
